services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
        VITE_GATEWAY_URL: ${VITE_GATEWAY_URL}
    container_name: rednorte-frontend-app
    ports:
      - "5173:5173"
    restart: unless-stopped
